




POST http://localhost:3003/api/blogs/ 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikppbm5lb24iLCJpZCI6IjYyNzEwMTI3YmExYTVhODE0ZjYzN2E5MSIsImlhdCI6MTY1MTU3MzA2OH0.jRencHiQ9xpnipAXDiM1ANcPH0JzIotsghObxXC-2xQ

{ "title": "Fish77 ", "author": "Fishing Pro: ", "url": "https://images.ctfassets.net/lufu0clouua1/Tr9lRGHXCS6GU4Kc8Qkg0/2f3a25a99c3f54c867ef5f8350aca5a3/King-Salmon.jpg", "likes": 27000000, "user":"Jinneon"}


